// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _241125_Speisekarte.Data;

#nullable disable

namespace _241125_Speisekarte.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241209065715_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("_241125_Speisekarte.Models.Speise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Bewertung")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notiz")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Speisen");
                });

            modelBuilder.Entity("_241125_Speisekarte.Models.Zutat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Beschreibung")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Einheit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Menge")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpeiseId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SpeiseId");

                    b.ToTable("Zutaten");
                });

            modelBuilder.Entity("_241125_Speisekarte.Models.Zutat", b =>
                {
                    b.HasOne("_241125_Speisekarte.Models.Speise", "Speise")
                        .WithMany("Zutaten")
                        .HasForeignKey("SpeiseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Speise");
                });

            modelBuilder.Entity("_241125_Speisekarte.Models.Speise", b =>
                {
                    b.Navigation("Zutaten");
                });
#pragma warning restore 612, 618
        }
    }
}
